# Generated by Django 4.2.4 on 2023-08-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
    ]
