# Generated by Django 4.2.4 on 2023-08-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_remove_task_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
    ]
